### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by AmaseCocoa** [graphene-fed/ActivityPub#1]
* [ ] Provide data classes to simplify reading nodeinfo
* [ ] Generate nodeinfo json from data class
* [ ] Provide functions that can generate Actor objects
